---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: /home/ansible/workspace/mvn/target/javaee7-simple-sample.war
      dest: /opt/tomcat/webapps/ 
